language: node_js
node_js: 
  - "lts/*"

dist: ubuntu:latest

cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache

stages:
  - name: pull-request
    if: type = pull_request

jobs:
  include:
    - stage: pull-request

      script:
        - cd functions
        - npm i
        - npm test